### ISSUE TITLE
Error loading types with 4.4.3

### ISSUE THREAD

**Issue by magJ** [formulajs/formulajs#181]
It looks like in the course of supporting `bundler` moduleResolution, #180 breaks formulajs when using `node` moduleResolution.

Our project started failing to build after updating to 4.4.3
```
error TS2307: Cannot find module '@formulajs/formulajs' or its corresponding type declarations.
  There are types at '/home/runner/actions-runner/_work/Formalize/Formalize/node_modules/@formulajs/formulajs/types/esm/index.d.mts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.
```

For now we will stay on the older version.
Sorry I don't have the time right now to investigate and understand the differences between the two moduleResolution strategies, but changing it in our project seems to break all sorts of other dependencies.

Hopefully it's possible to support both `node` and `bundler`, but if breaking `node` moduleResolution is intended, it doesn't seem like a change suitable for a minor version release.

**Comment by nicolashefti** [comment]
@magJ 4.4.4 is released fixing the issue regression. Let us know if this works for you.
